# Game plan
change the peak annotation to the fixed nearest genes to get a one to one correspondence in the peak to gene assignment! This will then work with the archvelo code! https://claude.ai/chat/9755e076-cd88-4062-8bb6-147e9adf2192

In [40]:
import pandas as pd
import numpy as np

In [41]:
path = r"C:\Users\Nikla\Documents\MoBi_Master_FS.3\Internship AG Höfer\DynaVelo_testing\data\peak_on_peaks_10_comps.csv"
peak_path = r"C:\Users\Nikla\Documents\MoBi_Master_FS.3\Internship AG Höfer\DynaVelo_testing\data\atac_peak_annotation_archvelo_proc.tsv"

In [42]:
df = pd.read_csv(path).T
peak_annotation = pd.read_csv(peak_path, sep = "\t", index_col=[0])

In [43]:
df.drop("Unnamed: 0", inplace=True)

In [44]:
peak_annotation

,chrom,start,end,gene,distance,peak_type
chr1:3445597-3446492,chr1,3445597,3446492,Gm1992,-20095.0,distal
chr1:3445597-3446492,chr1,3445597,3446492,Xkr4,0.0,distal
chr1:3670691-3671246,chr1,3670691,3671246,Xkr4,252.0,distal
chr1:3671350-3671824,chr1,3671350,3671824,Xkr4,0.0,promoter
chr1:4332187-4333082,chr1,4332187,4333082,Rp1,27232.0,distal
...,...,...,...,...,...,...
GL456216.1:48774-49639,GL456216.1,48774,49639,CAAA01118383.1,32894.0,distal
GL456216.1:50643-51473,GL456216.1,50643,51473,CAAA01118383.1,34763.0,distal
GL456216.1:56954-57800,GL456216.1,56954,57800,CAAA01118383.1,41074.0,distal
JH584292.1:12544-13464,JH584292.1,12544,13464,Vmn2r122,8972.0,distal
JH584295.1:1473-1976,JH584295.1,1473,1976,CAAA01147332.1,0.0,promoter

In [45]:
chromosome = peak_annotation.loc[:,"chrom"].values
start = peak_annotation.loc[:,"start"].values
end = peak_annotation.loc[:,"end"].values

combined_peak_names = [f"{chromosome[i]}:{start[i]}-{end[i]}" for i in range(len(chromosome))]
peak_annotation["peak_name"] = combined_peak_names
peak_annotation.set_index("peak_name", inplace = True)

peak_annotation

,chrom,start,end,gene,distance,peak_type
peak_name,,,,,,
chr1:3445597-3446492,chr1,3445597,3446492,Gm1992,-20095.0,distal
chr1:3445597-3446492,chr1,3445597,3446492,Xkr4,0.0,distal
chr1:3670691-3671246,chr1,3670691,3671246,Xkr4,252.0,distal
chr1:3671350-3671824,chr1,3671350,3671824,Xkr4,0.0,promoter
chr1:4332187-4333082,chr1,4332187,4333082,Rp1,27232.0,distal
...,...,...,...,...,...,...
GL456216.1:48774-49639,GL456216.1,48774,49639,CAAA01118383.1,32894.0,distal
GL456216.1:50643-51473,GL456216.1,50643,51473,CAAA01118383.1,34763.0,distal
GL456216.1:56954-57800,GL456216.1,56954,57800,CAAA01118383.1,41074.0,distal
JH584292.1:12544-13464,JH584292.1,12544,13464,Vmn2r122,8972.0,distal
JH584295.1:1473-1976,JH584295.1,1473,1976,CAAA01147332.1,0.0,promoter

In [47]:
peak_annotation["peak_name"]

KeyError: 'peak_name'

In [38]:
peak_annotation["absolute_distance"] = np.abs(peak_annotation["distance"].values)

unique_peak_annotation = (
    peak_annotation.sort_values("absolute_distance")
    .groupby(level=0)
    .first()
).drop(columns="absolute_distance")

In [39]:
unique_peak_annotation

,chrom,start,end,gene,distance,peak_type
GL456216.1:11246-12067,GL456216.1,11246,12067,CAAA01118383.1,-3814.0,distal
GL456216.1:13433-14343,GL456216.1,13433,14343,CAAA01118383.1,-1538.0,distal
GL456216.1:15799-16619,GL456216.1,15799,16619,CAAA01118383.1,0.0,promoter
GL456216.1:16825-17476,GL456216.1,16825,17476,CAAA01118383.1,945.0,distal
GL456216.1:25466-26383,GL456216.1,25466,26383,CAAA01118383.1,9586.0,distal
...,...,...,...,...,...,...
chrY:90808478-90809308,chrY,90808478,90809308,Gm47283,18028.0,distal
chrY:90810650-90811455,chrY,90810650,90811455,Gm47283,20200.0,distal
chrY:90812415-90813291,chrY,90812415,90813291,Gm47283,21965.0,distal
chrY:90824969-90825850,chrY,90824969,90825850,Gm21748,13327.0,distal
chrY:90828510-90829396,chrY,90828510,90829396,Gm21748,9781.0,distal

In [34]:
peak_annotation.loc["GL456216.1:25466-26383",:]

chrom            GL456216.1
start                 25466
end                   26383
gene         CAAA01118383.1
distance             9586.0
peak_type            distal
Name: GL456216.1:25466-26383, dtype: object

In [21]:
unique_peak_annotation

                        chrom  start  end  gene  distance  peak_type
GL456216.1:11246-12067    0.0    0.0  0.0   0.0       0.0        0.0
GL456216.1:13433-14343    0.0    0.0  0.0   0.0       0.0        0.0
GL456216.1:15799-16619    0.0    0.0  0.0   0.0       0.0        0.0
GL456216.1:16825-17476    0.0    0.0  0.0   0.0       0.0        0.0
GL456216.1:25466-26383    0.0    0.0  0.0   0.0       0.0        0.0
...                       ...    ...  ...   ...       ...        ...
chrY:90808478-90809308    0.0    0.0  0.0   0.0       0.0        0.0
chrY:90810650-90811455    0.0    0.0  0.0   0.0       0.0        0.0
chrY:90812415-90813291    0.0    0.0  0.0   0.0       0.0        0.0
chrY:90824969-90825850    0.0    0.0  0.0   0.0       0.0        0.0
chrY:90828510-90829396    0.0    0.0  0.0   0.0       0.0        0.0

[159930 rows x 6 columns]

In [12]:
peak_annotation_unique = peak_annotation.loc[
    peak_annotation.groupby(level=0)['distance'].idxmin(skipna=True)
]

KeyError: '[nan] not in index'

In [20]:
peaks.loc[df.index,:]["gene"]

chr1:6214291-6215185        4732440D04Rik
chr1:6214291-6215185               Rb1cc1
chr1:6222704-6223603               Rb1cc1
chr1:6222704-6223603        4732440D04Rik
chr1:6224909-6225755               Rb1cc1
                                ...
JH584304.1:72694-73583         AC149090.1
JH584304.1:89967-90870         AC149090.1
JH584304.1:97704-98608         AC149090.1
JH584304.1:103109-104001       AC149090.1
JH584304.1:106338-107238       AC149090.1
Name: gene, Length: 31056, dtype: object

In [ ]:
# The problem is that many peaks are assigned to two different genes. The archvelo code is trying to make a 1:1 correspondence between the genes and peaks

In [17]:
df['gene'] = peaks.loc[df.index,:]['gene']

ValueError: cannot reindex on an axis with duplicate labels